### ISSUE TITLE
any interest in a diodes sweep?

### ISSUE THREAD

**Issue by idank** [davidphilipbarr/Sweep#73]
Hello,

I took the sweep pcb and added diodes to it so the SDA/SCL pins can be freed for things like a trackball or OLED screen. I also made it hotswappable while I was at it. Apart from that, it's identical to the OG sweep.

Any interest in adding this variant to this repo?

![image](https://github.com/davidphilipbarr/Sweep/assets/1277636/80552dd2-3ed3-4fe1-b643-f6791acb973f)

**Comment by duckyb** [comment]
I don't think it's a good idea to add it to the repo because using diodes is not in the spirit of the sweep. Also since you are using a different pin-out of the micro controller this would be the only sweep that is not compatible in firmware.

I also made something similar to this but it has it's own repo: https://github.com/duckyb/urchin

**Comment by idank** [comment]
It doesn't have to use the same firmware, it could sit under `ferris/sweepdiode` or whatever. But the rest makes sense so I'll keep this separate, thanks!

**Comment by duckyb** [comment]
I know it doesn't _have_ to use the same firmware, but all other sweeps do. So this one would be the odd one out.
